# Generated by Django 4.0.3 on 2022-06-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default=0, upload_to='', verbose_name='프로필 사진'),
            preserve_default=False,
        ),
    ]
