# Generated by Django 4.0.3 on 2022-06-05 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0005_comment_last_modified_at_post_last_modified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='post_favorite', to=settings.AUTH_USER_MODEL, verbose_name='저장'),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='post_like', to=settings.AUTH_USER_MODEL, verbose_name='좋아요'),
        ),
    ]
