# Generated by Django 4.0.3 on 2022-05-01 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('category', models.CharField(choices=[('GEN', 'General issue'), ('ACC', 'Account issue'), ('ETC', 'etc.')], default='GEN', max_length=3)),
                ('title', models.CharField(max_length=64, verbose_name='질문 제목')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('email_checkbox', models.BooleanField(verbose_name='e-mail로 답변을 받겠습니다.')),
                ('phone_number', models.CharField(max_length=11, verbose_name='전화번호')),
                ('phone_checkbox', models.BooleanField(verbose_name='문자메시지로 답변을 받겠습니다.')),
                ('detail', models.TextField(verbose_name='내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='이미지')),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_creater', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('question', models.CharField(max_length=64, verbose_name='질문')),
                ('category', models.CharField(choices=[('GEN', 'General issue'), ('ACC', 'Account issue'), ('ETC', 'etc.')], default='GEN', max_length=3)),
                ('faq_answer', models.TextField(blank=True, verbose_name='답변')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_creater', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('last_modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='수정일시')),
                ('content', models.TextField(verbose_name='내용')),
                ('Inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.inquiry')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_creater', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('last_modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
