# Generated by Django 4.0.3 on 2022-04-17 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=30, verbose_name='질문')),
                ('category', models.CharField(choices=[('GEN', 'General issue'), ('ACC', 'Account issue'), ('ETC', 'etc.')], default='GEN', max_length=4)),
                ('answer', models.TextField(verbose_name='답변')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='최종 수정일시')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
        ),
    ]
