# Generated by Django 4.0.3 on 2022-04-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_faq_last_modifier_alter_faq_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GEN', 'General issue'), ('ACC', 'Account issue'), ('ETC', 'etc.')], default='GEN', max_length=3)),
                ('title', models.CharField(max_length=64, verbose_name='질문 제목')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail 주소')),
                ('phone_number', models.IntegerField(verbose_name='전화번호')),
                ('email_checkbox', models.BooleanField(verbose_name='문자메세지 전송 여부')),
                ('detail', models.TextField(verbose_name='내용')),
            ],
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('GEN', 'General issue'), ('ACC', 'Account issue'), ('ETC', 'etc.')], default='GEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='faq',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='최종 수정일시'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=64, verbose_name='질문'),
        ),
    ]
