# Generated by Django 4.0.3 on 2022-04-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_inquiry_created_at_inquiry_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='dateTimeOfUpload',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploades/', verbose_name='이미지'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='image_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='이미지 이름'),
        ),
    ]
