# Generated by Django 4.0.3 on 2022-05-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_inquiry_status_alter_inquiry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('REG', '문의 등록'), ('CHE', '접수 완료'), ('COM', '답변 완료'), ('NOT', '알림 완료')], default='REG', max_length=3),
        ),
    ]
