# Generated by Django 4.0.3 on 2022-04-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_alter_inquiry_email_checkbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='image_title',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='phone_checkbox',
            field=models.BooleanField(blank=True, null=True, verbose_name='문자메시지로 답변을 받겠습니다.'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='email_checkbox',
            field=models.BooleanField(blank=True, null=True, verbose_name='e-mail로 답변을 받겠습니다.'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phone_number',
            field=models.IntegerField(blank=True, verbose_name='전화번호'),
        ),
    ]
