# Generated by Django 4.0.3 on 2022-04-18 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0008_alter_inquiry_email_alter_inquiry_email_checkbox_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='내용')),
                ('Inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.inquiry')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Answer_writer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
