# Generated by Django 4.0.3 on 2022-04-18 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0009_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='last_modifier',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='Answer_modifier', to=settings.AUTH_USER_MODEL, verbose_name='최종 수정자'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='최종 수정일시'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='답변일시'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='created_by',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_creater', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
            preserve_default=False,
        ),
    ]
