# Generated by Django 4.0.3 on 2022-04-18 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0010_answer_last_modifier_answer_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='last_modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Answer_modifier', to=settings.AUTH_USER_MODEL, verbose_name='최종 수정자'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Answer_writer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_creater', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='전화번호'),
        ),
    ]
